CREATE TABLE version (
  id   BIGINT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  valid INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX (name)
);

CREATE TABLE user (
  id   BIGINT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);
